var x=new Date('06/02/2021');
console.log(x);
console.log(x.getDate());
console.log(x.getDay());
console.log(x.getFullYear());
console.log(x.getHours());
console.log(x.getMonth());
console.log(x.getSeconds);
console.log(x.getUTCMilliseconds());
console.log(x.setDate(05));
console.log(x.setFullYear(1998));
console.log(x.setHours(11));
console.log(x.setMinutes(25));